[rospy.client][INFO] 2016-06-04 16:20:17,129: init_node, name[/sensorring/gazebo_services], pid[11796]
[xmlrpc][INFO] 2016-06-04 16:20:17,129: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-06-04 16:20:17,130: ROS Slave URI: [http://cmeintel-desktop:42699/]
[xmlrpc][INFO] 2016-06-04 16:20:17,130: Started XML-RPC server [http://cmeintel-desktop:42699/]
[rospy.impl.masterslave][INFO] 2016-06-04 16:20:17,130: _ready: http://cmeintel-desktop:42699/
[xmlrpc][INFO] 2016-06-04 16:20:17,131: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-06-04 16:20:17,133: Registering with master node http://localhost:11311
[rospy.init][INFO] 2016-06-04 16:20:17,230: registered with master
[rospy.rosout][INFO] 2016-06-04 16:20:17,230: initializing /rosout core topic
[rospy.rosout][INFO] 2016-06-04 16:20:17,241: connected to core topic /rosout
[rospy.simtime][INFO] 2016-06-04 16:20:17,244: initializing /clock core topic
[rospy.simtime][INFO] 2016-06-04 16:20:17,259: connected to core topic /clock
[rosout][INFO] 2016-06-04 16:20:17,370: gazebo_services running
[rospy.internal][INFO] 2016-06-04 16:20:17,496: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-06-04 16:20:18,694: topic[/clock] adding connection to [http://cmeintel-desktop:35444/], count 0
[rospy.core][INFO] 2016-06-04 16:21:35,959: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-06-04 16:21:35,964: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-06-04 16:21:35,964: topic[/clock] removing connection to http://cmeintel-desktop:35444/
[rospy.topics][ERROR] 2016-06-04 16:21:35,965: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2016-06-04 16:21:35,965: signal-2
[rospy.internal][WARNING] 2016-06-04 16:21:35,971: Unknown error initiating TCP/IP socket to cmeintel-desktop:60543 (http://cmeintel-desktop:35444/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2016-06-04 16:21:36,131: signal_shutdown [atexit]
