[rospy.client][INFO] 2016-06-10 12:13:42,903: init_node, name[/gripper_left/gazebo_services], pid[7766]
[xmlrpc][INFO] 2016-06-10 12:13:42,904: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-06-10 12:13:42,905: ROS Slave URI: [http://cmeintel-desktop:39591/]
[xmlrpc][INFO] 2016-06-10 12:13:42,905: Started XML-RPC server [http://cmeintel-desktop:39591/]
[rospy.impl.masterslave][INFO] 2016-06-10 12:13:42,905: _ready: http://cmeintel-desktop:39591/
[xmlrpc][INFO] 2016-06-10 12:13:42,905: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-06-10 12:13:42,907: Registering with master node http://localhost:11311
[rospy.init][INFO] 2016-06-10 12:13:43,005: registered with master
[rospy.rosout][INFO] 2016-06-10 12:13:43,005: initializing /rosout core topic
[rospy.rosout][INFO] 2016-06-10 12:13:43,011: connected to core topic /rosout
[rospy.simtime][INFO] 2016-06-10 12:13:43,028: initializing /clock core topic
[rospy.simtime][INFO] 2016-06-10 12:13:43,041: connected to core topic /clock
[rosout][INFO] 2016-06-10 12:13:43,096: gazebo_services running
[rospy.internal][INFO] 2016-06-10 12:13:43,230: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-06-10 12:13:44,488: topic[/clock] adding connection to [http://cmeintel-desktop:38548/], count 0
[rospy.core][INFO] 2016-06-10 12:34:35,807: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-06-10 12:34:35,811: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-06-10 12:34:35,811: topic[/clock] removing connection to http://cmeintel-desktop:38548/
[rospy.topics][ERROR] 2016-06-10 12:34:35,812: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2016-06-10 12:34:35,812: signal-2
[rospy.internal][WARNING] 2016-06-10 12:34:35,813: Unknown error initiating TCP/IP socket to cmeintel-desktop:46903 (http://cmeintel-desktop:38548/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2016-06-10 12:34:35,919: signal_shutdown [atexit]
