[rospy.client][INFO] 2016-06-08 16:17:58,510: init_node, name[/arm_right/gazebo_services], pid[1329]
[xmlrpc][INFO] 2016-06-08 16:17:58,511: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-06-08 16:17:58,511: Started XML-RPC server [http://cmeintel-desktop:38835/]
[rospy.impl.masterslave][INFO] 2016-06-08 16:17:58,511: _ready: http://cmeintel-desktop:38835/
[rospy.registration][INFO] 2016-06-08 16:17:58,512: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2016-06-08 16:17:58,512: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2016-06-08 16:17:58,513: ROS Slave URI: [http://cmeintel-desktop:38835/]
[rospy.init][INFO] 2016-06-08 16:17:58,514: registered with master
[rospy.rosout][INFO] 2016-06-08 16:17:58,514: initializing /rosout core topic
[rospy.rosout][INFO] 2016-06-08 16:17:58,526: connected to core topic /rosout
[rospy.simtime][INFO] 2016-06-08 16:17:58,530: initializing /clock core topic
[rospy.simtime][INFO] 2016-06-08 16:17:58,562: connected to core topic /clock
[rosout][INFO] 2016-06-08 16:17:58,640: gazebo_services running
[rospy.internal][INFO] 2016-06-08 16:17:58,778: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-06-08 16:17:59,597: topic[/clock] adding connection to [http://cmeintel-desktop:43043/], count 0
[rospy.core][INFO] 2016-06-08 16:24:48,954: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-06-08 16:24:48,957: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-06-08 16:24:48,957: topic[/clock] removing connection to http://cmeintel-desktop:43043/
[rospy.topics][ERROR] 2016-06-08 16:24:48,958: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2016-06-08 16:24:48,958: signal-2
[rospy.internal][WARNING] 2016-06-08 16:24:48,958: Unknown error initiating TCP/IP socket to cmeintel-desktop:44044 (http://cmeintel-desktop:43043/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2016-06-08 16:24:49,122: signal_shutdown [atexit]
