[rospy.client][INFO] 2016-06-06 20:56:57,293: init_node, name[/gripper_left/gazebo_services], pid[6403]
[xmlrpc][INFO] 2016-06-06 20:56:57,294: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-06-06 20:56:57,294: Started XML-RPC server [http://cmeintel-desktop:34549/]
[rospy.init][INFO] 2016-06-06 20:56:57,294: ROS Slave URI: [http://cmeintel-desktop:34549/]
[rospy.impl.masterslave][INFO] 2016-06-06 20:56:57,294: _ready: http://cmeintel-desktop:34549/
[xmlrpc][INFO] 2016-06-06 20:56:57,294: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-06-06 20:56:57,295: Registering with master node http://localhost:11311
[rospy.init][INFO] 2016-06-06 20:56:57,394: registered with master
[rospy.rosout][INFO] 2016-06-06 20:56:57,395: initializing /rosout core topic
[rospy.rosout][INFO] 2016-06-06 20:56:57,398: connected to core topic /rosout
[rospy.simtime][INFO] 2016-06-06 20:56:57,400: initializing /clock core topic
[rospy.simtime][INFO] 2016-06-06 20:56:57,403: connected to core topic /clock
[rosout][INFO] 2016-06-06 20:56:57,431: gazebo_services running
[rospy.internal][INFO] 2016-06-06 20:56:57,585: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-06-06 20:56:59,445: topic[/clock] adding connection to [http://cmeintel-desktop:41055/], count 0
[rospy.core][INFO] 2016-06-06 21:01:05,825: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-06-06 21:01:05,829: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-06-06 21:01:05,829: topic[/clock] removing connection to http://cmeintel-desktop:41055/
[rospy.topics][ERROR] 2016-06-06 21:01:05,829: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2016-06-06 21:01:05,829: signal-2
[rospy.internal][WARNING] 2016-06-06 21:01:05,830: Unknown error initiating TCP/IP socket to cmeintel-desktop:47256 (http://cmeintel-desktop:41055/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2016-06-06 21:01:05,996: signal_shutdown [atexit]
