[rospy.client][INFO] 2016-06-09 14:06:51,593: init_node, name[/spawn_urdf_world], pid[28804]
[xmlrpc][INFO] 2016-06-09 14:06:51,595: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-06-09 14:06:51,596: Started XML-RPC server [http://cmeintel-desktop:44281/]
[rospy.impl.masterslave][INFO] 2016-06-09 14:06:51,596: _ready: http://cmeintel-desktop:44281/
[rospy.init][INFO] 2016-06-09 14:06:51,596: ROS Slave URI: [http://cmeintel-desktop:44281/]
[rospy.registration][INFO] 2016-06-09 14:06:51,600: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2016-06-09 14:06:51,602: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2016-06-09 14:06:51,696: registered with master
[rospy.rosout][INFO] 2016-06-09 14:06:51,697: initializing /rosout core topic
[rospy.rosout][INFO] 2016-06-09 14:06:51,715: connected to core topic /rosout
[rospy.simtime][INFO] 2016-06-09 14:06:51,726: initializing /clock core topic
[rospy.simtime][INFO] 2016-06-09 14:06:51,779: connected to core topic /clock
[rosout][INFO] 2016-06-09 14:06:51,799: Loading model xml from ros parameter
[rosout][INFO] 2016-06-09 14:06:51,831: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2016-06-09 14:06:51,921: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-06-09 14:06:53,628: topic[/clock] adding connection to [http://cmeintel-desktop:36601/], count 0
[rosout][INFO] 2016-06-09 14:06:54,385: Calling service /gazebo/spawn_urdf_model
[rosout][INFO] 2016-06-09 14:07:05,449: Spawn status: SpawnModel: Successfully spawned model
[rospy.core][INFO] 2016-06-09 14:07:05,449: signal_shutdown [atexit]
[rospy.internal][INFO] 2016-06-09 14:07:05,452: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-06-09 14:07:05,452: topic[/clock] removing connection to http://cmeintel-desktop:36601/
[rospy.topics][ERROR] 2016-06-09 14:07:05,452: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2016-06-09 14:07:05,452: atexit
[rospy.internal][WARNING] 2016-06-09 14:07:05,453: Unknown error initiating TCP/IP socket to cmeintel-desktop:51520 (http://cmeintel-desktop:36601/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

