[rospy.client][INFO] 2016-06-08 20:48:30,174: init_node, name[/spawn_gazebo_model], pid[28252]
[xmlrpc][INFO] 2016-06-08 20:48:30,180: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-06-08 20:48:30,180: Started XML-RPC server [http://cmeintel-desktop:33930/]
[rospy.impl.masterslave][INFO] 2016-06-08 20:48:30,180: _ready: http://cmeintel-desktop:33930/
[rospy.init][INFO] 2016-06-08 20:48:30,180: ROS Slave URI: [http://cmeintel-desktop:33930/]
[rospy.registration][INFO] 2016-06-08 20:48:30,190: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2016-06-08 20:48:30,190: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2016-06-08 20:48:30,281: registered with master
[rospy.rosout][INFO] 2016-06-08 20:48:30,281: initializing /rosout core topic
[rospy.rosout][INFO] 2016-06-08 20:48:30,293: connected to core topic /rosout
[rospy.simtime][INFO] 2016-06-08 20:48:30,324: initializing /clock core topic
[rospy.simtime][INFO] 2016-06-08 20:48:30,340: connected to core topic /clock
[rosout][INFO] 2016-06-08 20:48:30,361: Loading model xml from ros parameter
[rosout][INFO] 2016-06-08 20:48:30,425: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2016-06-08 20:48:30,602: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-06-08 20:48:31,583: topic[/clock] adding connection to [http://cmeintel-desktop:36211/], count 0
[rosout][INFO] 2016-06-08 20:48:31,683: Calling service /gazebo/spawn_urdf_model
[rosout][INFO] 2016-06-08 20:48:35,714: Spawn status: SpawnModel: Successfully spawned model
[rospy.core][INFO] 2016-06-08 20:48:35,714: signal_shutdown [atexit]
[rospy.internal][INFO] 2016-06-08 20:48:35,716: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-06-08 20:48:35,717: topic[/clock] removing connection to http://cmeintel-desktop:36211/
[rospy.topics][ERROR] 2016-06-08 20:48:35,717: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2016-06-08 20:48:35,717: atexit
[rospy.internal][WARNING] 2016-06-08 20:48:35,717: Unknown error initiating TCP/IP socket to cmeintel-desktop:53539 (http://cmeintel-desktop:36211/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

