[rospy.client][INFO] 2016-06-23 15:28:08,290: init_node, name[/ipa_pars/knowledge_parser_server_spawner], pid[13929]
[xmlrpc][INFO] 2016-06-23 15:28:08,290: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-06-23 15:28:08,291: Started XML-RPC server [http://cmeintel-desktop:37499/]
[rospy.init][INFO] 2016-06-23 15:28:08,291: ROS Slave URI: [http://cmeintel-desktop:37499/]
[rospy.impl.masterslave][INFO] 2016-06-23 15:28:08,291: _ready: http://cmeintel-desktop:37499/
[xmlrpc][INFO] 2016-06-23 15:28:08,291: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-06-23 15:28:08,292: Registering with master node http://localhost:11311
[rospy.init][INFO] 2016-06-23 15:28:08,391: registered with master
[rospy.rosout][INFO] 2016-06-23 15:28:08,391: initializing /rosout core topic
[rospy.rosout][INFO] 2016-06-23 15:28:08,394: connected to core topic /rosout
[rospy.simtime][INFO] 2016-06-23 15:28:08,395: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-06-23 15:28:08,397: Initialize KnowledgePaserServer ...
[rosout][INFO] 2016-06-23 15:28:08,407: KnowledgeParserServer initialize finished
[rosout][INFO] 2016-06-23 15:28:08,408: KnowledgeParserServer running waiting for knowledge to parse ...
[rospy.internal][INFO] 2016-06-23 15:28:08,408: topic[/ipa_pars/knowledge_parser_server/cancel] adding connection to [http://cmeintel-desktop:44759/], count 0
[rospy.internal][INFO] 2016-06-23 15:28:08,409: topic[/ipa_pars/knowledge_parser_server/goal] adding connection to [http://cmeintel-desktop:44759/], count 0
[rospy.internal][INFO] 2016-06-23 15:28:08,410: topic[/ipa_pars/knowledge_parser_server/feedback] adding connection to [/ipa_pars/knowledge_parser_client_spawner], count 0
[rospy.internal][INFO] 2016-06-23 15:28:08,411: topic[/ipa_pars/knowledge_parser_server/result] adding connection to [/ipa_pars/knowledge_parser_client_spawner], count 0
[rospy.internal][INFO] 2016-06-23 15:28:08,411: topic[/ipa_pars/knowledge_parser_server/status] adding connection to [/ipa_pars/knowledge_parser_client_spawner], count 0
[rospy.internal][INFO] 2016-06-23 15:28:08,632: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2016-06-23 15:28:08,961: Received a new goal:
[rosout][WARNING] 2016-06-23 15:28:09,681: Your executeCallback did not set the goal to a terminal status.  This is a bug in your ActionServer implementation. Fix your code!  For now, the ActionServer will set this goal to aborted
[rospy.internal][ERROR] 2016-06-23 15:28:09,718: Unable to initiate TCP/IP socket to cmeintel-desktop:43993 (http://cmeintel-desktop:44759/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2016-06-23 15:28:09,719: Unable to initiate TCP/IP socket to cmeintel-desktop:43993 (http://cmeintel-desktop:44759/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][WARNING] 2016-06-23 15:28:09,839: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2016-06-23 15:28:09,840: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][WARNING] 2016-06-23 15:28:09,840: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2016-06-23 15:28:09,840: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2016-06-23 15:28:10,009: topic[/ipa_pars/knowledge_parser_server/status] removing connection to /ipa_pars/knowledge_parser_client_spawner
[rospy.internal][WARNING] 2016-06-23 15:28:10,720: Unknown error initiating TCP/IP socket to cmeintel-desktop:43993 (http://cmeintel-desktop:44759/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2016-06-23 15:28:10,721: Unknown error initiating TCP/IP socket to cmeintel-desktop:43993 (http://cmeintel-desktop:44759/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-06-23 15:28:10,721: topic[/ipa_pars/knowledge_parser_server/cancel] removing connection to http://cmeintel-desktop:44759/
[rospy.internal][INFO] 2016-06-23 15:28:10,721: topic[/ipa_pars/knowledge_parser_server/goal] removing connection to http://cmeintel-desktop:44759/
[rospy.core][INFO] 2016-06-23 15:28:11,329: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-06-23 15:28:11,335: topic[/ipa_pars/knowledge_parser_server/result] removing connection to /ipa_pars/knowledge_parser_client_spawner
[rospy.internal][INFO] 2016-06-23 15:28:11,336: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-06-23 15:28:11,336: topic[/ipa_pars/knowledge_parser_server/feedback] removing connection to /ipa_pars/knowledge_parser_client_spawner
[rospy.impl.masterslave][INFO] 2016-06-23 15:28:11,336: signal-2
[rospy.core][INFO] 2016-06-23 15:28:11,500: signal_shutdown [atexit]
